name: Docker Image CI

on:
  push:
    branches: [ "master", "main", "12.1.*" ]
    paths-ignore:
      - '**/.vscode/**'
      - '**/docs/**'
      - '**/scripts/hooks/**'
      - '**/.env.example'
      - '**/.gitignore'
      - '**/CHANGELOG'
      - '**/LICENSE.txt'
      - '**/README.md'
      - '**/docker-compose*'
      - 'run.sh'
  pull_request:
    branches: [ "master", "main", "12.1.*" ]
    paths-ignore:
      - '**/.vscode/**'
      - '**/docs/**'
      - '**/scripts/hooks/**'
      - '**/.env.example'
      - '**/.gitignore'
      - '**/CHANGELOG'
      - '**/LICENSE.txt'
      - '**/README.md'
      - '**/docker-compose*'
      - 'run.sh'
  workflow_dispatch:

jobs:

  build:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Make scripts executable
        run: chmod +x *.sh

      - name: Load environment variables
        run: |
          source versions.env
          echo "IMAGE_BASE=${IMAGE_BASE}" >> $GITHUB_ENV

      - name: login to registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      

      - name: Build Docker image
        run: ./build.sh

      - name: Push Docker image
        run: ./push.sh
